language: java                

jdk:                         
  - oraclejdk8
  
branches:                 
only:
  - master
 
script:
  - mvn clean
  - mvn package jacoco:reportcoveralls:report

after_success:
  - bash <(curl -s https://codecov.io/bash) -t _your_token_
