language: java                

jdk:                         
  - oraclejdk8
  
branches:                 
only:
  - master
 
script:
  - mvn clean package

after_success:
  - echo "Process terminated successfully"
